"""
Configuration package
"""
from config.config import (
    AMAZON_SELLER_ID,
    AMAZON_SP_API_CLIENT_ID,
    AMAZON_SP_API_CLIENT_SECRET,
    AMAZON_SP_API_REFRESH_TOKEN,
    AMAZON_SP_API_REGION,
    AMAZON_MARKETPLACE_ID
)

__all__ = [
    'AMAZON_SELLER_ID',
    'AMAZON_SP_API_CLIENT_ID',
    'AMAZON_SP_API_CLIENT_SECRET',
    'AMAZON_SP_API_REFRESH_TOKEN',
    'AMAZON_SP_API_REGION',
    'AMAZON_MARKETPLACE_ID',
]
